### ISSUE TITLE
Disable Signup?

### ISSUE THREAD

**Issue by masonhensley** [moufette-tools/moufette#16]
Hello @jamalx31 - cool project!

I just deployed to heroku. Is there a config option to disable signup after I create the initial account? Looked around the repo and settings and didn't see anything, but it's been a late night 😅 .

**Comment by jamalx31** [comment]
Hi @masonhensley.
Sorry, I'm still working on the landing page and proper docs.
use can set the env variable `MULTIPLE_TEAMS=false`
that part is not perfect tho, if you have any suggestions plz lmk

**Comment by masonhensley** [comment]
Ahh, cool, thanks. Closing the issue. Thanks!

![image](https://user-images.githubusercontent.com/534165/89539474-c747ef00-d7c9-11ea-86f2-22b82bd7a337.png)

![image](https://user-images.githubusercontent.com/534165/89539632-037b4f80-d7ca-11ea-936a-167ebcd8eebc.png)

If I find some time to brush off my node.js/express, I'll try to open up a PR to hide the whole registration page & link to it based on that ENV var & or update the readme. 😎 


Steps for future users:
- add env to heroku 
- restart dyno
