### ISSUE TITLE
Steps to install locally?

### ISSUE THREAD

**Issue by Suleman-Elahi** [moufette-tools/moufette#17]
Can you list steps to run it locally? I don't have Heroku Paid account.

So far what I have done with the little knowledge I have:

1. `yarn install`
2. Renamed `.env.example` to `.env`
3. Edited `MONGO_URI` to `MONGODB_URI` in `.env` and added my MongoDB instance URL.
4. Inserted random string for `EXPRESS_SESSION_SECRET` and `JWT_SECRET`.
5. `yarn start`

I am getting this:

![image](https://user-images.githubusercontent.com/24384996/90780539-0161d680-e31c-11ea-8c9c-451fd1b3292a.png)

**Comment by jamalx31** [comment]
Sorry @Suleman-Elahi. I need to work on better docs.
seems like you did everything correctly, you just need to run the front dev server as well
so you need to run the two commands `yarn start` & `yarn front` simultaneously

**Comment by Suleman-Elahi** [comment]
Worked. Thanks.
![image](https://user-images.githubusercontent.com/24384996/90787844-c6af6c80-e322-11ea-8755-57760ebf1532.png)

There is new issue though.

![image](https://user-images.githubusercontent.com/24384996/90789567-aed8e800-e324-11ea-871b-c2505800bb16.png)

Cannot create features.

**Comment by jazzyjube** [comment]
Hi ! 
Thanks for this awesome tool ! 

I have the same issue as @Suleman-Elahi.
With a local installation, I reach the admin panel but impossible to add a feature (error : var was not provided) or save a widget (fatal error)

The project looks awesome I really want to use it and spread it around me ! 
Can't wait to find a solution :)
